services:
  spark-master:
    image: nitsvutt/spark:3.4.1
    hostname: spark-master
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - $COMMON_PATH/spark/event:/opt/spark/event
       - $COMMON_PATH/spark/work:/opt/spark/work
       - ./spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
    environment:
      - SPARK_MODE=master
    networks:
      - lakehouse_platform

  spark-history-server:
    image: nitsvutt/spark:3.4.1
    hostname: spark-history-server
    ports:
      - "19090:18080"
    depends_on:
      - spark-master
    volumes:
       - $COMMON_PATH/spark/event:/opt/spark/event
       - $COMMON_PATH/spark/work:/opt/spark/work
       - ./spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
    environment:
      - SPARK_MODE=history
    networks:
      - lakehouse_platform

  spark-worker-1:
    image: nitsvutt/spark:3.4.1
    hostname: spark-worker-1
    ports:
      - "9091:8081"
    depends_on:
      - spark-master
    volumes:
       - $COMMON_PATH/spark/event:/opt/spark/event
       - $COMMON_PATH/spark/work:/opt/spark/work
       - ./spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=3
      - SPARK_WORKER_MEMORY=6G
    networks:
      - lakehouse_platform

  spark-worker-2:
    image: nitsvutt/spark:3.4.1
    hostname: spark-worker-2
    ports:
      - "9092:8081"
    depends_on:
      - spark-master
    volumes:
       - $COMMON_PATH/spark/event:/opt/spark/event
       - $COMMON_PATH/spark/work:/opt/spark/work
       - ./spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=3
      - SPARK_WORKER_MEMORY=6G
    networks:
      - lakehouse_platform

networks:
  lakehouse_platform:
    external: true