services:
  postgresql:
    hostname: postgresql
    image: postgres:15-alpine3.18
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - $COMMON_PATH/postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$POSTGRESQL_USER
      - POSTGRES_PASSWORD=$POSTGRESQL_PASSWORD
      - POSTGRES_DB=metastore_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - iceberg_lakehouse_platform

  hive-metastore:
    hostname: hive-metastore
    image: nitsvutt/hive-metastore:3.0.0
    container_name: hive-metastore
    ports:
      - 9083:9083
    environment:
      - DATABASE_USER=$POSTGRESQL_USER
      - DATABASE_PASSWORD=$POSTGRESQL_PASSWORD
    depends_on:
      - postgresql
    networks:
      - iceberg_lakehouse_platform

networks:
  iceberg_lakehouse_platform:
    external: true